/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorizationModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "schema_version")]
    pub schema_version: String,
    #[serde(rename = "type_definitions", skip_serializing_if = "Option::is_none")]
    pub type_definitions: Option<Vec<crate::models::TypeDefinition>>,
}

impl AuthorizationModel {
    pub fn new(schema_version: String) -> AuthorizationModel {
        AuthorizationModel {
            id: None,
            schema_version,
            type_definitions: None,
        }
    }
}


