/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BatchCheckResponse {
    #[serde(rename = "allowed", skip_serializing_if = "Option::is_none")]
    pub allowed: Option<bool>,
    #[serde(rename = "_request", skip_serializing_if = "Option::is_none")]
    pub request: Option<crate::models::CheckRequest>,
    #[serde(rename = "err", skip_serializing_if = "Option::is_none")]
    pub err: Option<String>,
}

impl BatchCheckResponse {
    pub fn new() -> BatchCheckResponse {
        BatchCheckResponse {
            allowed: None,
            request: None,
            err: None,
        }
    }
}
