/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CheckNOfMRequest {
    #[serde(rename = "checks")]
    pub checks: Vec<crate::models::CheckRequest>,
    #[serde(rename = "n")]
    pub num: usize,
}

impl CheckNOfMRequest {
    pub fn new(checks: Vec<crate::models::CheckRequest>, num: usize) -> CheckNOfMRequest {
        CheckNOfMRequest {
            checks: checks,
            num: num,
        }
    }
}
