/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListObjectsRequest {
    #[serde(
        rename = "authorization_model_id",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_model_id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "relation")]
    pub relation: String,
    #[serde(rename = "user")]
    pub user: String,
    #[serde(rename = "contextual_tuples", skip_serializing_if = "Option::is_none")]
    pub contextual_tuples: Option<Box<crate::models::ContextualTupleKeys>>,
}

impl ListObjectsRequest {
    pub fn new(r#type: String, relation: String, user: String) -> ListObjectsRequest {
        ListObjectsRequest {
            authorization_model_id: None,
            r#type,
            relation,
            user,
            contextual_tuples: None,
        }
    }
}
