/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Node {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "leaf", skip_serializing_if = "Option::is_none")]
    pub leaf: Option<Box<crate::models::Leaf>>,
    #[serde(rename = "difference", skip_serializing_if = "Option::is_none")]
    pub difference: Option<Box<crate::models::UsersetTreePeriodDifference>>,
    #[serde(rename = "union", skip_serializing_if = "Option::is_none")]
    pub union: Option<Box<crate::models::Nodes>>,
    #[serde(rename = "intersection", skip_serializing_if = "Option::is_none")]
    pub intersection: Option<Box<crate::models::Nodes>>,
}

impl Node {
    pub fn new() -> Node {
        Node {
            name: None,
            leaf: None,
            difference: None,
            union: None,
            intersection: None,
        }
    }
}
