/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadAuthorizationModelResponse {
    #[serde(
        rename = "authorization_model",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_model: Option<Box<crate::models::AuthorizationModel>>,
}

impl ReadAuthorizationModelResponse {
    pub fn new() -> ReadAuthorizationModelResponse {
        ReadAuthorizationModelResponse {
            authorization_model: None,
        }
    }
}
