/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReadAuthorizationModelsResponse {
    #[serde(
        rename = "authorization_models",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_models: Option<Vec<crate::models::AuthorizationModel>>,
    #[serde(rename = "continuation_token", skip_serializing_if = "Option::is_none")]
    pub continuation_token: Option<String>,
}

impl ReadAuthorizationModelsResponse {
    pub fn new() -> ReadAuthorizationModelsResponse {
        ReadAuthorizationModelsResponse {
            authorization_models: None,
            continuation_token: None,
        }
    }
}
