/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

/// RelationReference : RelationReference represents a relation of a particular object type (e.g. 'document#viewer').



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationReference {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "relation", skip_serializing_if = "Option::is_none")]
    pub relation: Option<String>,
    #[serde(rename = "wildcard", skip_serializing_if = "Option::is_none")]
    pub wildcard: Option<serde_json::Value>,
}

impl RelationReference {
    /// RelationReference represents a relation of a particular object type (e.g. 'document#viewer').
    pub fn new(r#type: String) -> RelationReference {
        RelationReference {
            r#type,
            relation: None,
            wildcard: None,
        }
    }
}


