/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TupleOperation {
    #[serde(rename = "TUPLE_OPERATION_WRITE")]
    Write,
    #[serde(rename = "TUPLE_OPERATION_DELETE")]
    Delete,

}

impl ToString for TupleOperation {
    fn to_string(&self) -> String {
        match self {
            Self::Write => String::from("TUPLE_OPERATION_WRITE"),
            Self::Delete => String::from("TUPLE_OPERATION_DELETE"),
        }
    }
}

impl Default for TupleOperation {
    fn default() -> TupleOperation {
        Self::Write
    }
}




