/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TupleToUserset {
    #[serde(rename = "tupleset", skip_serializing_if = "Option::is_none")]
    pub tupleset: Option<Box<crate::models::ObjectRelation>>,
    #[serde(rename = "computedUserset", skip_serializing_if = "Option::is_none")]
    pub computed_userset: Option<Box<crate::models::ObjectRelation>>,
}

impl TupleToUserset {
    pub fn new() -> TupleToUserset {
        TupleToUserset {
            tupleset: None,
            computed_userset: None,
        }
    }
}


