/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Tuple {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<crate::models::TupleKey>>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl Tuple {
    pub fn new() -> Tuple {
        Tuple {
            key: None,
            timestamp: None,
        }
    }
}
