/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateStoreRequest {
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateStoreRequest {
    pub fn new(name: String) -> UpdateStoreRequest {
        UpdateStoreRequest { name }
    }
}
