/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WriteAuthorizationModelRequest {
    #[serde(rename = "type_definitions")]
    pub type_definitions: Vec<crate::models::TypeDefinition>,
    #[serde(rename = "schema_version", skip_serializing_if = "Option::is_none")]
    pub schema_version: Option<String>,
}

impl WriteAuthorizationModelRequest {
    pub fn new(type_definitions: Vec<crate::models::TypeDefinition>) -> WriteAuthorizationModelRequest {
        WriteAuthorizationModelRequest {
            type_definitions,
            schema_version: None,
        }
    }
}


